  export const articles = [
    {
      id: 1,
      isFeatured: true,
      category: "DSA",
      title: "DSA Pattern for problem solving",
      description: "Explore essential DSA patterns and proven strategies to solve coding problems efficiently.",
      author: "LinkdIn",
      date: "March 15, 2024",
      // readTime: "30 min read",
      tags: ["DSA", "Algorithms", "Sliding Window", "Two Pointers", "Problem Solving"],
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/600px-LinkedIn_logo_initials.png",
      articleUrl: "https://www.linkedin.com/feed/update/urn:li:activity:7294707300504600576/",
      isEmbeddable: false,
    },
    {
      id: 2,
      isFeatured: true,
      category: "System Design",
      title: "System Design Insights & Tutorials",
      description: "A curated collection of System Design articles and deep‑dive tutorials from the Hello, World!.",
      author: "glich.co",
      date: "March 15, 2024",
      readTime: "30 min read",
      tags: ["System Design", "Distributed Systems", "Scalability", "Architecture", "Tutorials"],
      imageUrl: "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/publication/logo/8715568a-af68-4718-adfc-016dbffd2b09/thumb_Group_55-1.png",
      articleUrl: "https://hw.glich.co/archive?tags=System+Design",
      isEmbeddable: true,
    },
    {
      id: 3,
      isFeatured: false,
      category: ["Interview Prep", "System Design"],
      title: "System Design Interview Questions",
      description: "An excellent, curated list of the most common questions asked in system design interviews.",
      author: "ByteByteGo",
      date: "April 25, 2024",
      // readTime: "25 min read",
      tags: ["System Design", "HLD", "LLD", "Interview Guide", "Architecture"],
      imageUrl: "https://bytebytego.com/_next/static/media/logo.5c3ffd6e.svg",
      articleUrl: "https://bytebytego.com/intro/system-design-interview",
      isEmbeddable: false,
    },
    {
      id: 4,
      isFeatured: false,
      category: ["System Design"],
      title: "System Design Preparation Guide",
      description: "A comprehensive guide to mastering system design concepts, real-world architecture patterns.",
      author: "LinkedIn",
      date: "April 25, 2024",
      // readTime: "25 min read",
      tags: ["System Design", "Load Balancing", "Caching", "Databases", "CAP Theorem"],
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/600px-LinkedIn_logo_initials.png",
      articleUrl: "https://www.linkedin.com/feed/update/urn:li:activity:7317535874886356993/",
      isEmbeddable: false,
    },
    {
      id: 5,
      isFeatured: true,
      category: ["CS Core", "Interview Prep"],
      title: "Interview Questions for CS Core Topics",
      description: "Most frequently asked DBMS and Operating System questions.",
      author: "Striver",
      date: "March 10, 2024",
      readTime: "30 min read",
      tags: ["CS Fundamentals", "DBMS", "Operating Systems", "Computer Networks", "SDE Core Sheet"],
      imageUrl: "https://takeuforward.org/static/media/TufLogowhite.c3d7f1c91c905c610f4a.png",
      articleUrl: "https://takeuforward.org/interviews/must-do-questions-for-dbms-cn-os-interviews-sde-core-sheet/",
      isEmbeddable: false,
    },
    {
      id: 6,
      isFeatured: false,
      category: ["CS Core", "Interview Prep"],
      title: "CS Core Interview Questions",
      description: "An excellent, curated list of the most common questions asked in CS Core interviews, from DBMS to OS.",
      author: "LinkedIn",
      date: "April 25, 2024",
      // readTime: "25 min read",
      tags: ["CS Core", "Operating Systems", "DBMS", "SQL", "OOP"],
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/600px-LinkedIn_logo_initials.png",
      articleUrl: "https://www.linkedin.com/feed/update/urn:li:activity:7333828245835919360/",
      isEmbeddable: false,
    },
    {
      id: 7,
      isFeatured: false,
      category: ["Interview Prep", "Web Development"],
      title: "Interview Questions for Frontend Developers",
      description: "A comprehensive guide to the most common frontend interview questions.",
      author: "InterviewBit",
      date: "March 8, 2024",
      // readTime: "20 min read",
      tags: ["Frontend", "JavaScript", "React", "HTML", "CSS"],
      imageUrl: "https://assets.interviewbit.com/assets/ibpp/brand-5c6255a15a1b1307a1b8a2bf0bcb149b1ff9513ab2854c7d391b3faf5f33848f.svg",
      articleUrl: "https://www.interviewbit.com/front-end-developer-interview-questions/",
      isEmbeddable: false,
    },
    {
      id: 8,
      isFeatured: false,
      category: ["Interview Prep", "Web Development"],
      title: "Frontend Developer Interview Questions",
      description: "Top 30 Frontend Developer Interview Questions and Answers to help you prepare for your next interview.",
      author: "roadmap.sh",
      date: "April 25, 2024",
      // readTime: "25 min read",
      tags: ["Frontend", "Web Vitals", "Browser Internals", "JavaScript Questions", "React Hooks"],
      // Corrected to the official logo
      imageUrl: "https://th.bing.com/th/id/OIP.fMI9Axdk9XljG2cSWww_sQAAAA?rs=1&pid=ImgDetMain",
      articleUrl: "https://roadmap.sh/questions/frontend",
      // Corrected based on site policy
      isEmbeddable: false,
    },
    {
      id: 9,
      isFeatured: false,
      category: "Interview Prep",
      title: "Backend Developer Interview Questions",
      description: "Top 75 Backend Developer Interview Questions With Detailed Answers",
      author: "Unstop",
      date: "April 25, 2024",
      // readTime: "25 min read",
      tags: ["Backend", "Node.js", "Express.js", "Databases", "API Design"],
      imageUrl: "https://d8it4huxumps7.cloudfront.net/uploads/images/unstop/svg/unstop-logo.svg",
      articleUrl: "https://unstop.com/blog/backend-interview-questions",
      isEmbeddable: false,
    },
    {
      id: 10,
      isFeatured: true,
      category: "Interview Prep",
      title: "Backend Developer Interview Questions",
      description: "37 Backend Interview Questions and Answers.",
      author: "HubSpot",
      date: "April 25, 2024",
      // readTime: "25 min read",
      tags: ["Backend", "Web Architecture", "Security", "REST API", "Microservices"],
      imageUrl: "https://www.hubspot.com/hubfs/assets/hubspot.com/web-team/WBZ/Blog%202021/Images/Logos/HubSpot%20Logo.svg",
      articleUrl: "https://blog.hubspot.com/website/backend-interview-questions",
      isEmbeddable: false,
    },
    {
      id: 11,
      isFeatured: false,
      category: "Web Development",
      title: "Web Development Interview Questions",
      description: "40 front-end developer in 2025 Interview Questions and Answers.",
      author: "LinkedIn",
      date: "April 25, 2024",
      // readTime: "25 min read",
      tags: ["Web Development", "Frontend", "React", "Angular", "JavaScript Concepts"],
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/600px-LinkedIn_logo_initials.png",
      articleUrl: "https://www.linkedin.com/feed/update/urn:li:activity:7325398546197708800/",
      isEmbeddable: false,
    },
    {
      id: 12,
      isFeatured: false,
      category: "Data Science",
      title: "Comprehensive Data Science Interview Q&A",
      description: "A complete guide with frequently asked questions and detailed answers for data science interviews.",
      author: "InterviewBit",
      date: "April 25, 2024",
      // readTime: "25 min read",
      tags: ["Data Science", "Python", "SQL", "Machine Learning", "Probability"],
      imageUrl: "https://assets.interviewbit.com/assets/ibpp/brand-5c6255a15a1b1307a1b8a2bf0bcb149b1ff9513ab2854c7d391b3faf5f33848f.svg",
      articleUrl: "https://www.interviewbit.com/data-science-interview-questions/",
      isEmbeddable: false,
    },
    {
      id: 13,
      isFeatured: false,
      category: "Data Science",
      title: "Fundamental Data Science Questions for Freshers",
      description: "A curated list of basic data science interview questions specifically for those starting their careers.",
      author: "GeeksforGeeks",
      date: "April 25, 2024",
      // readTime: "25 min read",
      tags: ["Data Science", "Beginner", "Statistics", "Deep Learning", "Data Mining"],
      // Replaced broken Bing link with official logo
      imageUrl: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/gfg_200x200-min.png",
      articleUrl: "https://www.geeksforgeeks.org/data-science-interview-questions-and-answers/",
      isEmbeddable: false,
    },
    {
      id: 14,
      isFeatured: false,
      category: "Data Science",
      title: "Top 50 Statistics Interview Questions",
      description: "Master the top 50 statistics questions essential for cracking a data science interview in 2025.",
      author: "Medium",
      date: "April 25, 2024",
      // readTime: "25 min read",
      tags: ["Statistics", "Data Science", "Probability", "Hypothesis Testing", "Regression"],
      imageUrl: "https://miro.medium.com/v2/resize:fit:2400/1*sHhtYhaCe2Uc3IU0IgKwIQ.png",
      articleUrl: "https://medium.com/%40thedatabeast/top-50-statistics-questions-to-crack-your-interview-in-data-science-in-2025-165aa1a41bb1",
      isEmbeddable: false,
    },
    {
      id: 15,
      isFeatured: false,
      category: "Data Science",
      title: "Curated 2025 Data Science Questions",
      description: "An expert-curated list of 31 essential questions for 2025, from a former Meta data scientist.",
      author: "DataLemur",
      date: "April 25, 2024",
      // readTime: "25 min read",
      tags: ["Data Science", "SQL", "Window Functions", "Joins", "Data Analysis"],
      imageUrl: "https://datalemur.com/og_image.webp",
      // Corrected URL to match the description (was pointing to interviewbit)
      articleUrl: "https://datalemur.com/blog/sql-interview-questions",
      isEmbeddable: false,
    },
    {
      id: 16,
      isFeatured: false,
      category: "Data Science",
      title: "Essential Data Science Interview Prep",
      description: "A collection of fundamental data science interview questions and answers to help you prepare.",
      author: "Turing",
      date: "April 25, 2024",
      // readTime: "25 min read",
      tags: ["Data Science", "Data Modeling", "Algorithms", "Big Data", "Data Wrangling"],
      imageUrl: "https://www.turing.com/assets/Turing-Wordmark_White.svg",
      articleUrl: "https://www.turing.com/interview-questions/data-science?utm_source=chatgpt.com",
      isEmbeddable: false,
    },



    
  ];